---
version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    colored:
        '()':  'colorlog.ColoredFormatter'
        format: '%(fg_cyan)s%(asctime)s - %(name)s%(reset)s - %(log_color)s%(levelname)s - %(reset)s%(message)s'
handlers:
    console:
        class: logging.StreamHandler
        formatter: colored
        stream: ext://sys.stdout
loggers:
    '':
        level: INFO
        handlers: [console]
...
