---
name: CI/Linting and Testing

on:
  pull_request:
    branches:
      - main

jobs:
  python_linting_and_testing:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
 
      - name: Install tox automation tool
        run: |
          pip install tox==3.26.0

      - name: Linting and testing
        run: tox

  dockerfile_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          failure-threshold: error
          dockerfile: Dockerfile.test
...
